game:
  fps: 60

window:
  caption: "My Project"
  background_color: [100, 100, 100]
  margin_size: 200 # Units: pixels.

grid:
  dim: 10 # Number of cells in width as well as height direction.
  color_map:
    0: [0, 0, 0]
    1: [255, 255, 255]
  show_gridlines: True
  grid_line_color: [150, 150, 150]
  grid_line_width: 2 # Units: pixels.